### ISSUE TITLE
Error when scheduling: "Data cannot occupy more than 10240 bytes when serialized"

### ISSUE THREAD

**Issue by afestein** [notifee/react-native-notifee#147] opened 2020-09-16 22:18 UTC
I'm seeing an error on Android when attempting to schedule a notification:

`[Error: Data cannot occupy more than 10240 bytes when serialized]`

It appears the data contained in the `Notification` fields I'm sending is too big (I can resolve it by reducing the size of the body, for example).

Here's an example of my `Notification` object:

```
  const notification: Notification = {
    android: {
      channelId: 'challenge-reminders',
      pressAction: {
        id: 'default',
        launchActivity: 'default',
      },
      smallIcon: 'ic_stat_notification_icon',
      sound: 'default',
    },
    body: 'Only 2 days to go. Keep it up!',
    data: {
      deepLink: 'xyz://app/challenges/my_challenge/progress',
      scheduler: 'local',
      trackingPayload:
        '{"channelId":"challenge-reminders","fireDate":1600293680171,"label":"en_US_challenge-reminders_day_7-reminder_1_2020-09-17","locale":"en_US","messageType":"day_7-reminder_1"}',
    },
    id: 'challenge-reminders/myChallenge/day_7/reminder_1/1_day',
    title: 'My Challenge',
  }
```

Any suggestions?

**Comment by mikehardy** [comment] 2020-09-16 23:54
Hi there! With apologies for closing, this is a dupe of #131 - there is some good discussion and progress there, the fix is the current item of development

**Closed by mikehardy** 2020-09-16 23:54 UTC
