### ISSUE TITLE
[iOS] Notification not showing up when app is in foreground

### ISSUE THREAD

**Issue by metervara** [notifee/react-native-notifee#86] opened 2020-06-11 19:19 UTC
Hi.

I'm trying to display a local notification on IOS while the app is in foreground but I can't get it to work. Android works fine but nothing shows up on IOS.

I have a minimal test project: https://github.com/metervara/RNNotifeeTest/

**Details**

* Using notifee version 0.7.1
* Debug builds (no license key)
* Requesting permission as described here: https://notifee.app/react-native/docs/ios/permissions#requesting-permissions
* Tested on iPhone 11/IOS 13.3 simulator (and 12.4)
* Tested on iPhone Xs/IOS 13.3.1 device

Project only has 3 dependencies:
```bash
"@notifee/react-native": "^0.7.1",
"react": "16.11.0",
"react-native": "0.62.2"
```

Relevant code for displaying the notification on IOS (I've tried a range of various settings without success):

```javascript
...

const foregroundPresentationOptions = {
  alert: true,
  badge: true,
  sound: true,
};

await notifee.displayNotification({
  title,
  body,
  ios: {
    critical: true,
    importance: AndroidImportance.HIGH,
    foregroundPresentationOptions,
  },
});

...
```

As far as I understand iOS silences notifications when the app is in foreground so I assume that is the issue. How can I override that default behaviour and display the notification?

**Comment by netbull** [comment] 2020-06-15 05:15
I think that is you rely on the OS to handle the display, the notifications are silences.

I send FCM as data message with info for the display and Notifee handles the display. Here the important part is to include `content-available` in the payload, so to work also if the app is in a background/killed state.

**Comment by metervara** [comment] 2020-06-15 07:34
Thanks.

I set up the project without Firebase to test notifications separately, so I have no incoming push and no FCM message. I'm creating a local notification with Notifee and displaying that directly using ```notifee.displayNotification```. Currently I'm only concerned about behaviour when the app is in the **foreground**.

According to [this guide](https://developer.apple.com/documentation/usernotifications/handling_notifications_and_notification-related_actions#2942082) the app is expected to handle the notification when in foreground, and it seems it should be possible to display it by executing the [completion handler](https://developer.apple.com/documentation/usernotifications/unusernotificationcenterdelegate/1649501-usernotificationcenter) of the [UNUserNotificationCenterDelegate](https://developer.apple.com/documentation/usernotifications/unusernotificationcenterdelegate) with the [relevant flags](https://developer.apple.com/documentation/usernotifications/unnotificationpresentationoptions/1649506-alert).

In Notifee those flags are implemented with [IOSForegroundPresentationOptions](https://notifee.app/react-native/reference/iosforegroundpresentationoptions), so I was expecting something like this to execute the completion handler with all flags enabled, showing the alert:

```javascript
notifee.displayNotification({
  title: 'A notification'
  body: 'The notification body',
  ios: {
    critical: true,
    importance: AndroidImportance.HIGH, // Documentation has Importance.HIGH which does not exist
    foregroundPresentationOptions: {
        alert: true,
        badge: true,
        sound: true,
    }
  },
});

```

I'm not up to speed with iOS, so it might be that I'm simply misreading the documentation. Can anyone verify or reject my assumption on this?

Should it be possible to display a local notification like this on iOS while the app is in foreground?

**Comment by netbull** [comment] 2020-06-15 07:51
@metervara I don't know where you read the documentation but this should work.

```js
import React, {useEffect} from 'react';
import notifee, {Importance} from '@notifee/react-native';

....

function App() {
  useEffect(() => {
    async function test() {
      await notifee.displayNotification({
        title: 'A notification',
        body: 'The notification body',
        ios: {
          critical: true,
          importance: Importance.HIGH,
        },
      });
    };

    test();
  }, []);
}
```

Have in mind these:
 - `Importance.HIGH` does exists
 - basically you don't need to set `foregroundPresentationOptions` in order to work
 - the default `importance` value is also good enough and it should work, so you can omit it. The difference on iOS between the default and HIGH is that the notification will be without sound/vibration. With HIGH you force the sound.

**Comment by metervara** [comment] 2020-06-15 09:27
thanks @netbull

I updated [my project](https://github.com/metervara/RNNotifeeTest/) with your suggestions but it's still not displaying a notification on iOS in foreground. The useEffect hook looks like this:

```javascript
useEffect(() => {
  async function displayNotification() {
    const settings = await notifee.requestPermission();
    if (settings.authorizationStatus >= IOSAuthorizationStatus.AUTHORIZED) {
      console.log('Has permission, Display a notification');
      await notifee.displayNotification({
        title: 'A notification',
        body: 'The notification body',
        ios: {
          critical: true,
          importance: AndroidImportance.HIGH,
        },
      });
      console.log('Displayed notification?');
    } else {
      console.log('User declined permissions');
    }
  }
  displayNotification();
}, []);
```

Any chance you could check my project out or provide a small example project to verify this is working as expected?

> * `Importance.HIGH` does exists

Seems it has been [renamed](https://github.com/notifee/react-native-notifee/issues/84#issuecomment-641815172_) in this [commit](https://github.com/notifee/react-native-notifee/commit/63eb430815647c610ceec1577cc596d1b0a86a41#diff-efd093703c52712604cdbf9dfdc055d1). I get undefined with version 0.7.1?

> * basically you don't need to set `foregroundPresentationOptions` in order to work

Ok, are they passed by default? I did a small [swift project](https://github.com/metervara/IOSLocalNotificationsTest) to test the native behaviour of this, and unless i pass the alert flag in the completion handler no Notification is shown?

**Comment by netbull** [comment] 2020-06-15 10:39
@metervara I'm not sure why there are two version lines.. in GitHub releases the latest version is 0.5.1 and on npm is 0.7.1.....

Currently the working version is 0.5.1. I was not able to trace what the changes are because I guess it's in `NotifeeCore.framework`

**Comment by mikehardy** [comment] 2020-06-15 16:45
Importance was Android-specific in practice (I gather?) and was moved to AndroidImportance as the package went from 0.5.1 to 0.7+. The tags should at least be visible on github to which code is where. Does this mean that in 0.7+ this no longer works? If so, then it might just be something about that Importance flag

I made a couple PRs against 0.5 that were merged, making it possible to run this project from master via a github link in your package.json so long as you cd into node-modules/@notifee/react-native and do a yarn + yarn build in postinstall - I mention that because it means you can play with solutions in the code (or just instrumenting it) and get it working then use patch-package to persist those while/if any PRs you make are merged

**Comment by netbull** [comment] 2020-06-15 16:57
@mikehardy the *Importance* is not problematic. Just it’s not mentioned in the docs for the change.

The issue is that the foreground messages does not work on version 0.7.1 and they work on 0.5.1. By “does not work” I mean they are not displayed while the app is in foreground.

I checked this on my existing project where everything works with version 0.5.1 and just with upgrade to 0.7.1 they are not displayed. However, the event *onForeground...* is emitted and I can see the payload. Also *notifee.displayNotification()* resolves with notification ID, so I guess the issue is somewhere in the NotifeeCore as I was not able to see anything in the commits without could be the issue..

**Comment by mikehardy** [comment] 2020-06-15 17:07
Okay - that's definitely for @Salakar  / @Ehesp  then - flagging for attention

Thank you for testing differentially to locate this

**Comment by mduthilleul** [comment] 2020-06-16 07:11
I can confirm the issue. 
Foreground notifications stopped working on iOS by switch from 0.5.1 to 0.7.1. No errors. A token is returned but nothing appears.

For informations, the problem is solved if reverting npm package to 0.5.1 but still having native iOS dependency to 0.7.1

**Comment by Salakar** [comment] 2020-06-16 13:50
Hey all, please try 0.7.2

**Closed** 2020-06-16 14:34 UTC

**Comment by netbull** [comment] 2020-06-16 14:37
@Salakar great! Will try it later.

**Comment by metervara** [comment] 2020-06-16 20:20
@Salakar works as expected in 0.7.2

**Comment by ahanusek** [comment] 2020-06-20 19:01
I've upgraded from 0.5.1 to 0.7.2 and now have this issue. I'm using code from the example:

```
function Screen() {
  async function onDisplayNotification() {
    // Create a channel 
    const channelId = await notifee.createChannel({
      id: 'default',
      name: 'Default Channel',
    });

    // Display a notification
    await notifee.displayNotification({
      title: 'Notification Title',
      body: 'Main body content of the notification',
      android: {
        channelId,
      },
    });
  }

  return (
    <View>
      <Button
        title="Display Notification"
        onPress={() => onDisplayNotification()}
      />
    </View>
  );
}
```

On 0.5.1 version, notification just showing up, on 0.7.2 displayNotifcation method is returning a notification id, but that one not showing up. Even if I add ios foregroundPresentationOptions nothing changes.

```
const notification = await notifee.displayNotification({
            title: 'Notification Title',
            body: 'Main body content of the notification',
            android: {
                channelId,
            },
            ios: {
                foregroundPresentationOptions: {
                    alert: true,
                    badge: true,
                    sound: true,
                }
            }
        });
```

Details

Debug builds 
Tested on iPhone Xs/IOS 13.3.1 device

**Comment by mikehardy** [comment] 2020-06-20 19:46
@ahanusek 

an ios flag you might try? (ios.critical = true)

> ```js
>       await notifee.displayNotification({
>         title: 'A notification',
>         body: 'The notification body',
>         ios: {
>           critical: true,
>         },
>       });

**Comment by ahanusek** [comment] 2020-06-20 20:08
@mikehardy Nothing has changed. 😢

**Comment by metervara** [comment] 2020-06-22 07:33
@ahanusek 

Maybe you can try my test project: https://github.com/metervara/RNNotifeeTest/
I tested on IOS13.3 Simulator and it works. 

I also have the importance flag set to HIGH

```javascript
await notifee.displayNotification({
  title: 'A notification',
  body: 'The notification body',
  ios: {
    critical: true,
    importance: AndroidImportance.HIGH,
  },
});
```

**Comment by mikehardy** [comment] 2020-06-22 14:58
It sees unexpected that the importance with an AndroidImportance value would mean anything in the ios config sub-object - @metervara can you confirm that it is required? and that you've done `npx react-native-clean-project` to make sure your build chain was clear of any unexpected iOS-native-Obj-C compilation caching etc?

**Comment by Salakar** [comment] 2020-06-22 15:54
@ahanusek
> BTW I'm trying to achieve behavior that notification displays only in the Notification Center and not popups on the screen when the app is in the foreground. Is it possible?

To do this, customise the [IOSForegroundPresentationOptions](https://notifee.app/react-native/reference/iosforegroundpresentationoptions) options:

```js
await notifee.displayNotification({
  title: 'A notification',
  body: 'The notification body',
  ios: {
	foregroundPresentationOptions: {
      alert: false,
      badge: true,
      sound: true,
	},
  },
});
```

As documented here: https://notifee.app/react-native/docs/ios/appearance

**Comment by ahanusek** [comment] 2020-06-22 17:04
@metervara
Yep, your example works but even without those flags:

```
await notifee.displayNotification({
        title: 'A notification',
        body: 'The notification body',
      });
```

So now I have to check if there is something wrong with my device or app.

@Salakar 
With this config, the notification doesn't appear in the Notification Center.
