### ISSUE TITLE
[Android, iOS?] Cannot get initial notification

### ISSUE THREAD

**Issue by nicolas-adamini** [notifee/react-native-notifee#93] opened 2020-06-29 09:00 UTC
# Bug report

Maybe a duplicate of https://github.com/notifee/react-native-notifee/issues/89

## Scenario
- App is closed
- A notification is received via **Firebase Cloud Messaging**
- The notification is pressed

## Result
✅  The app should open
❌   I should  get the initial notification logged in the console

## Code snippet

```
const bootstrap = async () => {
    const initialNotification = await notifee.getInitialNotification();
    console.log('notifee - initialNotification', initialNotification);
}
```

## Deps

` "@react-native-firebase/messaging": "7.1.4"`
`"@notifee/react-native": "0.9.0",`
` "react-native": "0.62.2",`

**Comment by Salakar** [comment] 2020-06-30 04:07
Thanks for the report - this is 100% a duplicate of #89 of which I'll hopefully have a fix in for by the end of the week.

Let's track on #89. Thanks for raising this issue 🎉

**Closed by Salakar** 2020-06-30 04:07 UTC
Labels: bug
