### ISSUE TITLE
fresh Android build failure

### ISSUE THREAD

**Issue by kaminskypavel** [notifee/react-native-notifee#12] opened 2020-02-10 22:05 UTC
Hi Team, 

I'm trying to take notifee for a ride, but am getting this error on a fresh install

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformNativeLibsWithMergeJniLibsForDebug'.
> More than one file was found with OS independent path 'lib/x86/libc++_shared.so'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```
steps to reproduce: 
1. use @expo bare typescript generator
2. yarn add @notifee/react-native
3. react-native run-android

**SOLUTION ✅** (taken from nonotest's reply [here ](https://github.com/react-native-community/jsc-android-buildscripts/issues/80)) :

**app\build.grade**
```
android {
....
packagingOptions {
       pickFirst 'lib/x86/libc++_shared.so'
       pickFirst 'lib/x86_64/libjsc.so'
       pickFirst 'lib/arm64-v8a/libjsc.so'
       pickFirst 'lib/arm64-v8a/libc++_shared.so'   <-------------- 💡
       pickFirst 'lib/x86_64/libc++_shared.so'
       pickFirst 'lib/armeabi-v7a/libc++_shared.so'
   }
....
}
```

hope this helps

**Comment by kaminskypavel** [comment] 2020-02-10 22:08
here the commit that did the trick https://github.com/kaminskypavel/react-native-ts-playground/commit/627b025d5a0456be504aa322e0a969eb25ad5d2f

**Comment by mikehardy** [comment] 2020-02-10 22:31
@Salakar another pickFirst workaround :thinking: dupe of #11 I think

**Comment by Salakar** [comment] 2020-02-10 23:31
This is the Flipper plugin causing this - we're going to remove it for now in the next release, we can't have nice things 😭

**Comment by Salakar** [comment] 2020-02-13 21:02
This has been fixed in the latest release, thanks!

**Closed by Salakar** 2020-02-13 21:02 UTC
