### ISSUE TITLE
Foreground Service notification not removing after resolve()

### ISSUE THREAD

**Issue by ashokkumar88** [notifee/react-native-notifee#203] opened 2020-11-28 09:07 UTC
Hi,
I am displaying a notification with `asForegroundService:true` with two action buttons. Also registered the `registerForegroundService` event. But when click on the Action button it does not remove the notification. Below is my code

```
notifee.registerForegroundService((notification) => {
  return new Promise(resolve => {    
    
    notifee.onForegroundEvent(({ type, detail }) => {       
      notifee.cancelDisplayedNotification(notification.id)
      if (type === EventType.ACTION_PRESS && detail.pressAction.id === 'stopnotification') {
        console.log(type,detail); // i am getting this on console
        return resolve();
      }
    });

  });
});
```

**Comment by mikehardy** [comment] 2020-11-28 14:04
Hey @ashokkumar88 - I assume this is android? I assume you are on the current release version? Can you specify those details?

Also, if you could provide a minimal App.js - that shows this problem with no other code necessary so we could drop it in a test app (like that generated by https://github.com/mikehardy/rnfbdemo/blob/master/notifee-demo.sh ) that would help us determine where the problem is

Thanks in advance - hopefully we can get this fixed up quickly

**Comment by ashokkumar88** [comment] 2020-11-28 14:14
@mikehardy Yes, it is in android using the latest version. IOS not checked. I will provide a minimal App.js shortly.

**Comment by mikehardy** [comment] 2020-11-28 14:20
just a quick note that "latest version" is dependent on time and sometimes issues span releases while doing triage/fix - for the avoidance of doubt: that's version v0.15.1 ?

**Comment by ashokkumar88** [comment] 2020-11-28 15:15
yes, it is 0.15.1

**Comment by ashokkumar88** [comment] 2020-11-28 17:41
App.js

```
import React, {Component} from 'react';  
import {StyleSheet, Text, View,TouchableOpacity} from 'react-native'; 
import notifee,{AndroidImportance,EventType} from '@notifee/react-native'; 

notifee.registerForegroundService((notification) => {
  return new Promise(resolve => {    
    
    notifee.onForegroundEvent(({ type, detail }) => { 
      console.log(notification);      
      if (type === EventType.ACTION_PRESS && detail.pressAction.id === 'stopnotification') {
        console.log(type,detail)
        return resolve();
      }
    });

  });
});  
 
const displayNotification = async () => {
    const channelId = await notifee.createChannel({
      id: 'alerts',
      name: 'Notification Channel',
    });

  await notifee.displayNotification({
  title: 'Foreground Service Notification',
  body: 'Press the Quick Action to stop the service',
  android: {
    channelId,
    actions: [
      {
        title: 'Stop',
        pressAction: {
          id: 'stopnotification',
        },
      },
    ],
  },
});
}


  
type Props = {};  
export default class App extends Component<Props> {  
  render() {  
    return (  
      <View style={styles.container}>  
        <Text style={styles.welcome}>Welcome to React Native!</Text>  
        <TouchableOpacity onPress={this.displayNotification}><Text style={styles.instructions}>Display Notification</Text>  </TouchableOpacity>
        
      </View>  
    );  
  }  
}  
  
const styles = StyleSheet.create({  
  container: {  
    flex: 1,  
    justifyContent: 'center',  
    alignItems: 'center',  
    backgroundColor: '#F5FCFF',  
  },  
  welcome: {  
    fontSize: 20,  
    textAlign: 'center',  
    margin: 10,  
  },  
  instructions: {  
    textAlign: 'center',  
    color: '#333333',  
    marginBottom: 5,  
  },  
});
```

**Comment by mikehardy** [comment] 2020-11-28 17:44
@ashokkumar88 fantastic - thanks for the reproduction. Sorry again that you are having trouble but we should be to find a resolution now

**Comment by sambegin** [comment] 2021-03-22 12:35
Any news on this? Anything we can do to help to resolve the issue?

**Comment by helenaford** [comment] 2021-03-27 20:15
Hi @sambegin, a p/r just went up internally with a fix. I was able to replicate this bug locally by doing a series of steps:
1. Start Service
2. Hot Reload while the service is still running, this will clear the service
3. Start Service again
4. call `resolve()` at any point (e.g. by pressing `stop()` action), and the service fails to clear.

This seems to be linked with hot reloading, it can be fixed in its current state by reinstalling the app which i understand isn't ideal.

The fix will expose a new API `notifee.stopForegroundService` so it's not reliant on any binding.

**Comment by helenaford** [comment] 2021-04-01 17:22
Release 1.3.0 includes the new API method `stopForegroundService`. Please see[ release notes](https://notifee.app/react-native/docs/release-notes#130) for more details, and the updated documentation (https://notifee.app/react-native/docs/android/foreground-service). To prevent any breaking changes, `resolve()` will still work, but the preferred method is to use `stopForegroundService`.

**Closed by helenaford** 2021-04-01 17:22 UTC
Labels: Platform: Android, bug, needs-review
