### ISSUE TITLE
[iOS] Not getting events from onForegroundEvent / onBackgroundEvent

### ISSUE THREAD

**Issue by MystL** [notifee/react-native-notifee#233] opened 2021-01-21 04:59 UTC
Hi,

I integrated notifee to display a Local Push Notifications upon receiving remote messages from `@react-native-firebase/messaging`. The Notification was displayed fine in both Android and iOS.

However, upon tapping on the Push Notifications (in iOS), I noticed that there isn't any `PRESS`, `ACTION_PRESS` or `DISMISSED` EventType fired from the callback of `onForegroundEvent` or `onBackgroundEvent`. The only event received was `DELIVERED`, on Android all the events was firing well, but not on iOS. 

A little bit about the implementation

Displaying a Push Notification
```
notifee.displayNotification({
  "android": {
    "channelId": "",
    "pressAction": {
      "id": "default",
      "launchActivity": "default"
    },
    "smallIcon": "ic_launcher"
  },
  "body": "Message Body of PN",
  "data": {
    "key1": "value1"
  },
  "ios": {
    "sound": "default"
  },
  "title": "Title of PN"
})
```

onForegroundEvent listener
```
notifee.onForegroundEvent(({ type, detail }) => {
	console.log('Type', type)
	switch (type) {
		case EventType.PRESS:
			console.log('Expecting to get this event when user taps on the Push Notification..');
			break;
		case EventType.DELIVERED:
			console.log('Only getting this event on iOS');
			break;
		}
	});
```

from the above, other than `DELIVERED` i'm not getting any other events. Whereas based on this documentation https://notifee.app/react-native/reference/eventtype#press

it says the following, but I don't seems to get the event when pressing on the Push Notification..

> PRESS
Event type is sent when a notification has been pressed by the user.
On Android, notifications must include an android.pressAction property for this event to trigger.
On iOS, this event is always sent when the user presses a notification.

implementation dependencies:
"@notifee/react-native": "^1.0.0",
"@react-native-firebase/messaging": "^7.9.0",
"react": "16.11.0",
"react-native": "^0.63.3",

Hope to get some assistance / advise.

TIA.

**Comment by MystL** [comment] 2021-01-21 10:32
Update: I tried downgrading the library to `0.15.2` and turns out the callbacks are triggering, but not working on `0.16.0 or `1.0.0`. 🤔

**Comment by mikehardy** [comment] 2021-01-21 11:38
@MystL sorry this is happening to you - This report is really valuable - especially comparing the versions and noting 0.15.x appeared to work and 0.16+ does not - there was some major re-packaging there to support Apple Silicon, nearly all the work was on the iOS side so perhaps there was a regression. I'll investigate this

@helenaford for completeness / collaboration - I've been meaning to figure out why iOS e2e has been hanging in CI but works locally, so this is 2 items with one pass for me, I'll attempt to add e2e cover to the notification action events and have those exercised successfully in CI so we should expose the problem fully, I'll post info here as I get it

**Comment by MystL** [comment] 2021-01-22 01:54
@mikehardy Thanks for following up, hope to hear from you soon.

**Comment by helenaford** [comment] 2021-01-22 02:52
Hey, @mikehardy that's cool. let me know what you find with e2e tests. I had a quick look with one of my apps that uses `Notifee` and it works fine, receiving both foreground and background events. @MystL are you testing on iOS 14?

**Comment by MystL** [comment] 2021-01-22 02:59
> Hey, @mikehardy that's cool. let me know what you find with e2e tests. I had a quick look with one of my apps that uses `Notifee` and it works fine, receiving both foreground and background events. @MystL are you testing on iOS 14?

@helenaford Yea that's right, I was testing on iOS 14.2 and observed this behaviour.

**Comment by helenaford** [comment] 2021-01-22 03:24
I'm testing on 14.3 but that shouldn't make a difference. Are you observing this in debug or release mode?

**Comment by MystL** [comment] 2021-01-22 03:28
> I'm testing on 14.3 but that shouldn't make a difference. Are you observing this in debug or release mode?

I was on debug mode

**Comment by helenaford** [comment] 2021-01-22 04:03
The only other thing I can think of suggesting is removing your Pods and running `pod install ` confirming the output lists `1.0.0` for RNNotifee: 
`Installing RNNotifee 1.0.0 (was 0.15.2)`.  <-- won't have the previous version printed in brackets if you clear Pods first. 

Apologies if you have done this step... It's helped a few people out before while they've switched between versions. 
If that doesn't work, it could be something in the new version that is causing this, I'm just unable to see it at this time.

**Comment by MystL** [comment] 2021-01-22 04:10
Thanks @helenaford , actually when I first started integrating Notifee I was first on `1.0.0` as the project did not have any Notifee dependencies before, just that when I realized the callbacks wasn't firing in iOS but was all good in Android, I downgraded it to `0.15.2` instead and got it worked on both Platforms. 

The process was as you mentioned but i first did `pod deintegrate` first and then do a `pod install` and I could see the version are reflected as wanted.

Wondering if there are any other things i missed 🤔

**Comment by helenaford** [comment] 2021-01-22 04:28
No that really should have been it, thanks for the info... hopefully the e2e tests will expose the issue.

**Comment by helenaford** [comment] 2021-01-31 19:27
hey, I've updated @mikehardy's script here: `https://github.com/helenaford/rnfbdemo` with event listeners to show that they are coming through. If you wanted to try it out, you just have to run it locally by `./notifee-demo.sh`, output of events looks like this:
![example-output](https://user-images.githubusercontent.com/14185925/106395155-94895700-63f8-11eb-933c-35525ee05b40.png)

**Comment by mikehardy** [comment] 2021-01-31 19:33
Yep - and I just merged that, so if you clone that repo now (or if you already had it cloned, update it ?) it will have her changes ready to go for you - thanks!

**Comment by Markuson** [comment] 2021-03-04 10:42
Any news regarding this issue? looks like it's not working for me either.

**Comment by mikehardy** [comment] 2021-03-04 13:19
It is marked as blocked waiting for customer-response and we've provided a script that creates a clean app for test reproduction - the problem is that we do not appear to be able to reproduce it in a minimal reproduction, using that script. Have you tried it? 

https://github.com/mikehardy/rnfbdemo/blob/master/notifee-demo.sh

Here is the commit where @helenaford added the listeners to demonstrate: https://github.com/mikehardy/rnfbdemo/commit/ff79a82d4494f7610e106bee60ad4bbc5e6988ed#diff-0ecb3c74e031923f53f5b2da02158860e687afac32ad5cb37a0652ebc471f250

**Comment by Markuson** [comment] 2021-03-04 14:25
I'm trying the demo, but this demo does not work with remote messages. is it?

I mean, a cannot throw a message with the app in the background/quit , as there's only the option to throw the message trough a button in the app.

To be able to throw a message while the app is in the background, i'll need to get a token form FCM.

I find the problem while throwing messages when the app is in the background or in quit state.

**Comment by mikehardy** [comment] 2021-03-04 14:38
Notifee -> on-device local notifications - the demonstration shows that because that is Notifee's focus
FCM -> cloud messages (may have notification, data, or mixed payload), may or may not be delivered, all sorts of subtle cases

What exactly do you mean by "message", in what context?

If what you want is guaranteed delivery of a cloud message, then you must ask firebase cloud messages to send a cloud message with a notification payload.

Is that what you mean? An FCM with notification payload?

At that point, the firebase-ios-sdk will have control, your react-native app will not get control.
firebase-ios-sdk will post a local on-device notification

In that case, it may be that Notifee does not understand that the local notification is related (since Notifee did not post the local notification) so it may not fire the listeners. @helenaford is that correct? That Notifee does not fire listeners for local notifications it does not create? I seem to remember some issue / PR traffic around that but not sure if that use case is resolved

**Comment by Markuson** [comment] 2021-03-04 14:48
What I'm trying to achieve is:

I'm sending data-only notifications trough Firebase cloud console (with data, and without notification field). when the app receive it, i can handle the notification received and throw a push notification to the phone using `notifee.displayNotification()`.  This works as expected on iOs and on Android.

Once I press to the notification, on Android `notifee.onBackgroundEvent()` or `notifee.getInitialNotification()` is executed as expected, depending on the app state.

But on iOS none of this listeners are triggering. The only listener is triggered its `notifee.onBackgroundEvent()` qhen the app is delivered.

So I cannot detect if I pressed a specific notification or not.

I'm trying to achieve this because i want to control if the notification i received through the cloud is already on the notifications tray, so i won't launch it again, or i can delete the previous notifiation and display the new one. So I won't have repeated notifications on my tray.

**Comment by mikehardy** [comment] 2021-03-04 14:56
Excellent, that is more clear.

Assumptions:
1. You use FCM REST API (or similar) to request a data-only cloud message? (please note the term "message", if you send a data-only message it is not a notification, it is a data-only FCM - the terms are precise or communication is difficult)
2. That data-only cloud message from FCM is received?
3. react-native-firebase setBackgroundMessageHandler is called? Your app does receive control?
4. You then use Notifee APIs to post a local on-device notification with action buttons?
5. The user taps the notification or one of the buttons?
6. Notifee's event handlers (background or foreground) do *not* fire on iOS?

A lot of assumptions but that is what I understand from your comments. Please correct any incorrect assumptions.

If those assumptions are correct, what I don't understand is why 6 is not working, when our demonstration effectively skips 1 through 3, but starting at 4 the demonstration uses Notifee APIs to post a local notification, so then 5 and 6 work. If you are doing step 4 correctly, steps 5 and 6 should work in your app as they work in the demo. Steps 1 through 3 should not matter.

**Comment by Markuson** [comment] 2021-03-04 15:05
> Excellent, that is more clear.
> 
> Assumptions:
> 
> 1. You use FCM REST API (or similar) to request a data-only cloud message? (please note the term "message", if you send a data-only message it is not a notification, it is a data-only FCM - the terms are precise or communication is difficult)
> 2. That data-only cloud message from FCM is received?
> 3. react-native-firebase setBackgroundMessageHandler is called? Your app does receive control?
> 4. You then use Notifee APIs to post a local on-device notification with action buttons?
> 5. The user taps the notification or one of the buttons?
> 6. Notifee's event handlers (background or foreground) do _not_ fire on iOS?
> 
> A lot of assumptions but that is what I understand from your comments. Please correct any incorrect assumptions.
> 
> If those assumptions are correct, what I don't understand is why 6 is not working, when our demonstration effectively skips 1 through 3, but starting at 4 the demonstration uses Notifee APIs to post a local notification, so then 5 and 6 work. If you are doing step 4 correctly, steps 5 and 6 should work in your app as they work in the demo. Steps 1 through 3 should not matter.

1. YES, I use FCM REST API, it's not a message perse, it's a data-only FCM as you said. I convert it to message using `notifee.displayNotification()`.
2. data-only is received, YES. And i can take it, and "convert" it on a notification using `notifee.displayNotification()`.
3. setBackgroundMessageHandler is called in always when app is background or quit (on iOs it's slowlier than on Android, but doesn't matter).
4. I use notifee APIs, but i do not use action buttons, should i use action buttons always on iOS?
5. the user taps the notification, not the buttons because I don't put any buttons. I will try to put buttons now and see what's happening.
6. NO, notifee event handlers don't fire on iOS, also tried firebase/messaging handlers, but not working.

thanks for your help @mikehardy you are  lifesaver!

**Comment by mikehardy** [comment] 2021-03-04 15:25
4. Hmm - buttons or not, when using the Notifee APIs I do not think it should matter. Notifee should "know" it posted the local notification, and it should fire the event handlers when the user interacts with the notification (tap, swipe away, any interaction)
5. Okay, so the user interacts and then...
6. event handlers should fire! They fire in the demo, but not in your app!?

That is the strangest thing. You can see the demo just uses Notifee API calls to post a local notification for the user (step 4), you can do step 5 as the user, then the handlers fire which is what we want with step 6.

We have confirmation that apps created with notifee-demo.sh show step 6 working - that is vital! Please try the script and confirm a clean app shows event handlers firing.

My assumption now is that notifee-demo.sh creates an app where step 6 works, you see event handlers firing.

If that's the case, then there is a difference between a clean app, and your app, and the goal is to find the difference, and it's a project-specific issue

If that is not the case, then we have a Notifee bug.

**Comment by Markuson** [comment] 2021-03-05 07:31
I've created a simple app. with react-native init. And just aded the code concerning notifications. Same results...

Including action buttons `notifee.onBackgroundEvent()` triggers when you press them. but don't trigger when pressing on the notification only.

I'll try to upload it in my github.

**Comment by Markuson** [comment] 2021-03-08 13:04
Hi, 

Making some more tests, I've just found one thing.

When a notification is triggered while the app is in background or quit state. If you press to the notification then, it will trigger the foreground listener. Otherwise, if you clear the notification, it will trigger the background listener.

For me it's good news cause I can manage it to know if the notification has been opened or cleared, for now, I don't really care if it's triggering foreground or background listener. Just want to be aware that the user do something with the notification.

**Comment by mikehardy** [comment] 2021-03-08 13:42
@Markuson that's actually a duplicate of #262 - it's an artifact of iOS bringing the app to front before executing code (our listener) so by the time the listener executes it *is* foreground. iOS-only

**Comment by helenaford** [comment] 2021-03-08 13:46
Can this be closed?

**Comment by Markuson** [comment] 2021-03-08 13:49
there's aome issues regarding notification handling on ios, so if the other issue remains open, we can close this or viceversa.

I've just notice another detail. if I press clear all on the notification tray on ios, no event is triggered, so this will be a problem also.

**Comment by helenaford** [comment] 2021-03-23 01:01
OK, will close this in favour of #262. As of, the event for clear all, @Markuson can you make that into its own issue please? It may be that it's not possible to listen to that event.

**Closed by helenaford** 2021-03-23 01:01 UTC
Labels: Platform: iOS, bug, under-review
