### ISSUE TITLE
No task registered for key app.notifee.notification-event

### ISSUE THREAD

**Issue by patrickreiner** [notifee/react-native-notifee#111] opened 2020-07-20 22:02 UTC
Hi,

I have all notifications working in iOS and Android, whether app is in foreground, background, or quit. No issues.

For whatever reason, I am getting a warning that states "No task registered for key app.notifee.notification-event"

I am not sure what this means or what the purpose of this warning is, as all functionality is implemented and working correctly. Any help regarding what I can do to silence this warning is greatly appreciated.

**Comment by Doosra-App** [comment] 2020-07-21 12:13
Hi patrick, I am getting issues while the app is in killed state in ios. How to achieve this issue?

**Comment by helenaford** [comment] 2020-07-23 11:52
Hi, thanks for letting us know. I'll see if I can replicate this locally.

**Comment by Doosra-App** [comment] 2020-07-23 11:53
Thanks, Helena.

**Comment by mars-lan** [comment] 2020-08-16 01:30
Also getting the same issue with Android. Seems to be triggered by notifications delivered when the app is running in the background.

**Comment by mars-lan** [comment] 2020-09-03 12:33
Any update @helenaford ?

**Comment by helenaford** [comment] 2020-09-03 14:39
@AndrewMorsillo the issue with the app not opening when the notification is tapped is a known issue (#121) . Can be fixed by adding `'launchActivity: 'default'` inside `pressAction`.

**Comment by supermar1010** [comment] 2020-09-04 09:59
I'm getting the same warning, additionally the `onForegroundEvent` does not fire. Everytime I do something that should trigger that event, I get the warning. I'm experiencing this on android

**Comment by helenaford** [comment] 2020-09-04 23:00
Think I got to the bottom of this. It happens when `notifee.onBackgroundEvent(async ({ type, detail }) => {...}` is missing. Please try putting this in your application. There maybe something we can do to check if your app has this or not before sending out an event.

**Comment by afestein** [comment] 2020-09-15 01:26
I'm also seeing this message in the console when the app is not running and a local notification is received.

I expected the `notifee.onBackgroundEvent` to fire, but instead I see this. (Note that I have the async listener function set up as described above).

I want this because I'd like to fire a tracking event when notifications are received. (Note that it works fine when the app is already running in the background). The user experience is good (opening the deeplink works fine), just something is missing with the background event.

**Comment by helenaford** [comment] 2020-09-15 12:03
@afestein are you seeing it on Android, iOS or both?

**Comment by yochidaniel** [comment] 2020-09-15 16:36
Hi,
I am getting this on Android.
The way I have reproduced it is by setting a firebase background listener and when getting a notification I am trying to set local notification using displayNotification.

`messaging().setBackgroundMessageHandler(async remoteMessage => {
    console.log('Message handled in the background!', remoteMessage.data);
    await  sendNotification(remoteMessage.data); // function that calles notifee.displayNotification
});`

Seems like the warning message ( "No task registered for key app.notifee.notification-event") is coming right after executing  
`notifee.displayNotification`

**Comment by helenaford** [comment] 2020-09-15 17:51
@yochidaniel thanks, did you set the `notifee.onBackgroundEvent` too?

**Comment by yochidaniel** [comment] 2020-09-15 18:39
No i didn't and everything is working perfectly without it.
However, I have run another test while setting it on top. So now my index.js looks like:

`messaging().setBackgroundMessageHandler(sendNotification); //send notification is a function that send local notification (see function below)

notifee.onBackgroundEvent(async ({ type, detail }) => {
    console.log('got notification');
});`

`xport async  function sendNotification(notification){
    let message = notification.data;
    console.log('send notification using notifee');
    let header = message.header;
    let subTitle = message.subTitle;
    const channelId = await notifee.createChannel({
        id: 'default',
        name: 'Default Channel',
        sound: 'alert1',
    });
    notifee.displayNotification({
        title: header,
        body: subTitle,
        android: {
            channelId,
            pressAction: {
                id: 'default',
            },
            timestamp: Date.now(), // 8 minutes ago
            showTimestamp: true,
        },
    })
        .then(resp => {
            console.log('sendNotification resp: ',resp)
        })
        .catch(err => {
            console.log('sendNotification error: ',err);
        })
}`

As result, the warning message was not showing anymore. But now I have 2 functions that listen to background notifications.
Also, for some reason, the notification is only vibrating without any sound.

**Comment by afestein** [comment] 2020-09-15 21:58
Thanks for the reply @helenaford. This warning is Android-only for me. 

On iOS I get nothing at all (no event either). This is a bit off-topic, but I suspect that might be due to missing iOS background event support as mentioned in [this comment](https://github.com/notifee/react-native-notifee/issues/1#issuecomment-625808121).

**Comment by helenaford** [comment] 2020-09-29 10:56
Mmm yeah, think there's another issue for iOS all together. Left a comment on the issue you linked (146) to say it's being looked into. 

The current fix on this issue is to set `notifee.onBackgroundEvent` but don't think it's the permanent fix so will leave this open for now.

**Comment by mikehardy** [comment] 2020-09-29 14:08
I see this as well but don't have a solid reproduction myself, yet.
I've started building a from-scratch demonstrator currently here (it'll move but does exist here now) and I don't have the list of steps that showed the problem but I saw it with this one even so we're close to a repro: https://github.com/mikehardy/rnfbdemo/commit/fc7e943ca95fe1777300985f31db2a075d2da4a5 / https://github.com/mikehardy/rnfbdemo/blob/master/notifee-demo.sh

**Comment by helenaford** [comment] 2020-09-29 15:05
@mikehardy ah cool. nice script. I have a permanent fix in mind to do what RNFB does which doesn't require the background handler to be set.

**Comment by helenaford** [comment] 2020-11-12 23:05
Fix is included in the latest release (v0.15.1). Please see release notes [here](https://notifee.app/react-native/docs/release-notes).

**Closed by helenaford** 2020-11-12 23:05 UTC
