### ISSUE TITLE
await notifee.displayNotification not firing notification on release build

### ISSUE THREAD

**Issue by siddharthpvi** [notifee/react-native-notifee#385] opened 2021-09-18 23:23 UTC
I am scheduling local notification. It works in when use react-native run-android but when i make android release build at that time local notification is not firing.

I have already spent 2 days and finally decided to raise issue here.

Hope i will get the right answer in quick time.

Thanks

**Comment by mikehardy** [comment] 2021-09-19 14:37
Hi there! Can you please include your package.json, and details on your testing environment regarding what device model and Android version is in use for the debug and release tests? You may be able to learn more from using adb logcat also, unfiltered

**Comment by princefishthrower** [comment] 2021-09-19 20:29
@mikehardy Same for me. Notifications work fine on the android simulators and on iPhone devices but they do not appear on android devices. I've followed the [installation instructions](https://notifee.app/react-native/docs/installation) and am using the latest notifee version, 2.0.0.

@siddharthpvi did you find a fix here?

**Comment by mikehardy** [comment] 2021-09-19 21:06
I'm going to have to try some more tests, at least for me right now in my dev app environment I'm popping up notifee notifications ![Screenshot_20210919-160406.jpg](https://user-images.githubusercontent.com/782704/133943010-fe0840fa-bd10-4a95-916c-a8ab2fca6b07.jpg)

**Comment by princefishthrower** [comment] 2021-09-19 21:49
@mikehardy - is this on a real device or a simulator?

**Comment by mikehardy** [comment] 2021-09-20 00:03
Real device. OnePlus 6T android 11

**Comment by helenaford** [comment] 2021-09-20 00:09
@princefishthrower @siddharthpvi did you set up your license key in the app (https://notifee.app/react-native/docs/license-keys)?

**Comment by mikehardy** [comment] 2021-09-20 00:29
Oh sorry for the spam but for the avoidance of doubt it is a full release build

**Comment by helenaford** [comment] 2021-09-22 10:43
Could you try the latest release(v3.0.0)?

**Comment by princefishthrower** [comment] 2021-09-22 13:10
@mikehardy @helenaford - the cause was likely the licensing issue @helenaford mentioned. For now we are going with an (admittedly less feature) solution with [`react-native-notifications`](https://github.com/wix/react-native-notifications).

**Comment by helenaford** [comment] 2021-09-22 16:54
@princefishthrower thanks for letting us know what the source of the bug was. Will close this.

**Closed by helenaford** 2021-09-22 16:54 UTC
