### ISSUE TITLE
Per build type notifee license (notifee.config.json)

### ISSUE THREAD

**Issue by tad3j** [notifee/react-native-notifee#73] opened 2020-06-01 07:17 UTC
Could you please implement a better way for loading notifee license, so we can build staging and production builds without always having to modify `notifee.config.json`?

I think notifee should allow us to easily build in dev environment (automatically loading the right keys from file(s)) but also let us provide license through ENV variables in staging and production builds (CI/CD).

**Comment by Salakar** [comment] 2020-06-01 08:36
Hey, this is in progress on #67 and also a duplicate of #37 so will go ahead and close so we can track there. Thanks

**Closed by Salakar** 2020-06-01 08:36 UTC
