### ISSUE TITLE
Not getting notifications when the app is background or killed state in ios

### ISSUE THREAD

**Issue by Doosra-App** [notifee/react-native-notifee#104] opened 2020-07-08 07:47 UTC
The notifications are working fine in foreground in ios, but not working in background and killed state.
I changed the version to 0.9.1 but getting the issue app.notifee.notification.event is not supported. Supported event types are app.notifee.notification-event and app.notifee.notification-background-event. How can I fix this issue?

**Comment by Ehesp** [comment] 2020-07-08 12:00
Could you show some code please?

**Comment by Doosra-App** [comment] 2020-07-08 12:24
import messaging from '@react-native-firebase/messaging';
import notifee, {
EventType,
AndroidImportance,
AndroidStyle,
AndroidLaunchActivityFlag,
} from '@notifee/react-native';

notifee.onBackgroundEvent(async ({type, detail}) => {
console.log('background event', detail);
const {notification} = detail;
if (type === EventType.DISMISSED) {
notifee.cancelNotification(notification.id);
}
else if (type === EventType.ACTION_PRESS && detail.pressAction.id === 'otp')
{
Clipboard.setString(notification.data.otp);
Toast.show('Code copied!');
}
});

messaging().setBackgroundMessageHandler(async remoteMessage => {
console.log('message', remoteMessage);
const {data} = remoteMessage;
const channelId = await notifee.createChannel({
id: data.type,
name: data.type,
importance: AndroidImportance.HIGH,
sound: data.sound,
});
await notifee.setNotificationCategories([
{
id: 'otp',
actions: [
...(data.type === 'otp'
? [
{
id: 'otp',
title: data.otp,
},
]
: []),
],
},
]);
await notifee.displayNotification({
title: data.title,
body: data.body,
data: {
...(data.type === 'otp' && {
sender_id: data.sender_id,
is_read: data.is_read,
is_spam: data.is_spam,
sender_name: data.sender_name,
sliced_sender_id: data.sliced_sender_id,
otp: data.otp,
type: data.type,
route: data.route,
}),
},
android: {
channelId,
sound: data.sound,
smallIcon: 'ic_notification',
...(data.type === 'plan_reminder' && {
style: {
type: AndroidStyle.BIGTEXT,
text: data.body,
},
}),
color: '#33aabb',
pressAction: {
id: 'default',
launchActivity: 'default',
launchActivityFlags: [AndroidLaunchActivityFlag.NEW_TASK],
},
actions: [
...(data.type === 'otp'
? [
{
title: '<b>' + data.otp + '</b>',
pressAction: {id: 'otp'},
},
]
: []),
],
},
ios: {
categoryId: 'otp',
sound: 'Beacon',
},
});
});

**Comment by Doosra-App** [comment] 2020-07-08 12:24
The code is in index.js file

**Comment by Doosra-App** [comment] 2020-07-15 08:27
@Ehesp The comment is posted 7 days back but no reply. My product release is stopped because of this issue. Can you please give me the reply?

**Comment by Doosra-App** [comment] 2020-07-17 08:02
Hi,

We've been asking for a solution for one week now. We are unable to move
forward since this is an issue for us to release an app update.
For a paid product, the service you are providing is abysmal. Your TAT is 3
days, to begin with, and it's still okay if that was adhered to. After
giving a response to a ticket 9 days ago, it is disappointing that a follow
up is taking so long.

I request you to kindly respond as soon as possible because this is getting
very frustrating every time we reach out to you.

Thanks,
Pratyush
Product Manager
doosra.com

**Comment by mikehardy** [comment] 2020-07-17 15:47
I think we're stumped. We can't reproduce this - that was my thought when I saw your previous messages but I didn't think it added value for you so I didn't comment. It works in my project at least so I'm surprised. I would post an example github repo built off `npx react-native init` with the minimum possible integration for notifee to demonstrate the behavior and post it here

**Comment by Doosra-App** [comment] 2020-07-18 07:15
Hi Mike,

When can we expect this example repo to be sent?

**Comment by helenaford** [comment] 2020-07-18 13:06
Hi Pratyush, Mike was suggesting that you should produce an example app to demonstrate the bug you're having. If that's possible? A barebones codebase where you do `npx react-native init` and install `notifee`, to a GitHub repo you can share with us.

**Comment by Doosra-App** [comment] 2020-07-21 12:38
Hi Helena,

As previously mentioned, we have provided the code we have used to get
notifications when the app is in a killed state. It is working on Android
but for some reason is not working on iOS devices. We are using the latest
version of Notifee (0.10.0) and also the latest version of React-Native
Firebase Messaging (7.4.2).

Kindly let us know what might be the issue here, since your team may have
faced while developing the product. In case, these solutions do not work
then we can work on what you suggested since it will some effort and time
from our side to do it.

Thanks.

**Comment by helenaford** [comment] 2020-07-23 11:52
Hi, that's understandable regarding the example repo. Could you show us the log output? I'm trying to work out how '`app.notifee.notification.event`' is printed because that's not in the code. If we could see more of the log, it will help to piece it together.  With issue #111, when I saw it I thought it could be the same as what you're experiencing but I see the notifications for them are still coming through, and only a warning in the logs is shown

**Comment by Doosra-App** [comment] 2020-07-23 12:16
@helenaford Can you see the attached image?[
![Screenshot 2020-07-21 at 8 10 23 PM](https://user-images.githubusercontent.com/66351546/88285273-6ff74880-cd0c-11ea-8cfe-7571cf7cb59c.png)
](url)

**Comment by helenaford** [comment] 2020-07-23 12:37
thanks for the screenshot! have you tried removing your Podfile.lock Pods & node_modules, I think something might have cached from an older version.

**Comment by uranashel95** [comment] 2020-07-24 01:13
I got the same issues. No notifications in background mode.

**Comment by helenaford** [comment] 2020-08-07 10:48
Closing this as the issue seems to be resolved. @uranashel95 please if you still are experiencing problems create a new issue.

**Closed by helenaford** 2020-08-07 10:48 UTC
Labels: blocked: customer-response
