### ISSUE TITLE
Error: Notifee native module not found., js engine: hermes

### ISSUE THREAD

**Issue by MahmonirB** [notifee/react-native-notifee#158] opened 2020-09-28 09:14 UTC
when I use notifee for display cloud message firebase notification, i get this error in app:

**Error: Notifee native module not found., js engine: hermes**

there is my  **package.json**:
```json
{
  "name": "ostadkar_provider_app",
  "version": "4.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint .",
    "pre-release": "npx jetify",
    "swaggerGenerate": "ts-node bin/generate-swagger.ts",
    "start:android": "react-native run-android & react-native start",
    "storybook": "react-native run-android & react-native start ",
    "storybook:android": "ENVFILE=.env.storybook react-native run-android & react-native start",
    "format": "prettier --write 'src/**/*.{js,jsx,ts,tsx,json,css,scss,md}'",
    "post-build": "sentry-cli releases set-commits $npm_package_version --auto && sentry-cli releases files $npm_package_version upload-sourcemaps --rewrite  ./android/app/build/generated/assets/react/release/index.android.bundle  ./android/app/build/generated/sourcemaps/react/release/index.android.bundle.map",
    "post-build-windows": "sentry-cli releases set-commits %npm_package_version% --auto && sentry-cli releases files %npm_package_version% upload-sourcemaps --rewrite  ./android/app/build/generated/assets/react/release/index.android.bundle  ./android/app/build/generated/sourcemaps/react/release/index.android.bundle.map"
  },
  "dependencies": {
    "@notifee/react-native": "^0.13.0",
    "@react-native-community/async-storage": "^1.11.0",
    "@react-native-community/cli": "^4.9.0",
    "@react-native-community/netinfo": "^5.9.1",
    "@react-native-firebase/analytics": "^7.6.1",
    "@react-native-firebase/app": "^8.4.1",
    "@react-native-firebase/messaging": "^7.8.3",
    "@sentry/react-native": "^1.5.0",
    "@sentry/wizard": "^1.1.4",
    "@storybook/addon-actions": "^6.0.21",
    "@storybook/addons": "^6.0.21",
    "@storybook/react-native": "^5.3.21",
    "axios": "^0.19.0",
    "code-push": "^3.1.3",
    "color": "^3.1.2",
    "core-js": "^2.6.11",
    "core-js-bundle": "^3.6.4",
    "core-js-pure": "^3.6.4",
    "core-util-is": "^1.0.2",
    "hermes-engine": "0.4.1",
    "lodash": "^4.17.15",
    "material-design-icons": "^3.0.1",
    "prettier": "^2.0.2",
    "pretty-quick": "^2.0.1",
    "react": "16.11.0",
    "react-hook-form": "^5.7.2",
    "react-native": "0.62.2",
    "react-native-axios": "^0.17.1",
    "react-native-bundle-visualizer": "^2.1.1",
    "react-native-code-push": "^6.2.0",
    "react-native-config": "^0.12.0",
    "react-native-debugger": "^1.1.0",
    "react-native-device-info": "^5.2.1",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-global-props": "^1.1.5",
    "react-native-image-picker": "^2.3.0",
    "react-native-material-dropdown": "^0.11.1",
    "react-native-modal": "^11.5.6",
    "react-native-navigation-hooks": "^2.21.0",
    "react-native-push-notification": "^5.0.1",
    "react-native-reanimated": "^1.10.1",
    "react-native-screens": "^2.9.0",
    "react-native-svg": "^9.11.1",
    "react-native-uuid": "^1.4.9",
    "react-native-vector-icons": "6.6.0",
    "react-navigation": "^4.3.9",
    "react-navigation-stack": "^1.9.3",
    "react-redux": "^7.2.0",
    "redux": "^4.0.5"
  },
  "devDependencies": {
    "@babel/core": "^7.10.3",
    "@babel/runtime": "^7.10.3",
    "@react-native-community/eslint-config": "^2.0.0",
    "@types/color": "^3.0.0",
    "@types/jest": "^24.0.17",
    "@types/lodash": "^4.14.137",
    "@types/react": "^16.9.2",
    "@types/react-native": "^0.60.6",
    "@types/react-test-renderer": "^16.9.0",
    "babel-jest": "^26.1.0",
    "babel-loader": "^8.0.6",
    "babel-plugin-module-resolver": "^3.2.0",
    "eslint": "^7.3.1",
    "eslint-config-airbnb": "^18.1.0",
    "eslint-plugin-import": "^2.20.2",
    "eslint-plugin-jsx-a11y": "^6.2.3",
    "eslint-plugin-react": "^7.19.0",
    "husky": "^3.0.4",
    "jest": "^26.1.0",
    "lint-staged": "^9.2.2",
    "metro": "^0.59.0",
    "metro-react-native-babel-preset": "^0.59.0",
    "react-dom": "16.8.6",
    "react-test-renderer": "16.13.1",
    "swagger-typescript-codegen": "^3.0.1",
    "ts-node": "^8.6.2",
    "typescript": "^3.7.5"
  },
  "jest": {
    "preset": "react-native"
  },
  "husky": {
    "hooks": {
      "pre-commit": "pretty-quick lint-staged --staged"
    }
  },
  "pretty-quick": {
    "format": [
      "git add"
    ]
  },
  "lint-staged": {
    "*.{js,jsx}": [
      "eslint --fix",
      "git add"
    ]
  }
}
```

**Comment by mikehardy** [comment] 2020-09-28 14:47
I believe your project has an autolinking problem, the module simply is not integrated correctly

For the avoidance of doubt and to perhaps save you time by focusing on the correct area (your project, or this module): I am 99.99% sure that you have not integrated the module correctly and the solution will be in project-specific code, with no action taken here. So I wouldn't wait for any definitive troubleshooting here, I would look very carefully at your integration

You might try `npx react-native-clean-project` followed by a `pod install` again (assuming it's iOS, you did not mention platform) ?

**Comment by MahmonirB** [comment] 2020-09-28 18:03
Thanks for your reply. The platform is android now, and about the problem it is important to say when I comment notifee notification code, the project build successful (I am using fast refresh). In my idea, hermes is doubtfull here.

**Comment by MahmonirB** [comment] 2020-09-28 18:04
I remove node modules and install it several times.

**Comment by mikehardy** [comment] 2020-09-28 19:08
🤔  It seems intuitive that if the problem is that the Notifee module is not integrated correctly then commenting out the code that attempts to use it will allow you to proceed (though without Notifee of course, not actually what you want).

Removing node_modules is one thing `npx react-native-clean-project` is completely next level - it even wipes out the DerivedData build cache from Xcode (frequently necessary, though as you mention you are having difficulty on android).

This still smells like an auto-linking issue to me. I have successful builds from a fresh project like so: https://github.com/mikehardy/rnfbdemo/blob/master/notifee-demo.sh

If you clone that repo and run that script, you will get a clean + empty demonstration of notifee working from scratch, and it also shows that I unfortunately cannot reproduce your problem

**Comment by MahmonirB** [comment] 2020-09-28 19:14
I'll clone it and try manual linking way, then come back again. Thank for your attention.

**Closed** 2020-10-23 12:23 UTC
Labels: blocked: customer-response

**Comment by AyoubMoustahfid** [comment] 2021-08-31 14:53
I installed the package, but when I want to run the application it shows me this problem "" Error: Notifee native module not found. "", please give me a solution to this problem


![image](https://user-images.githubusercontent.com/47373251/131524885-ae172c1d-ddf8-4905-b4e6-bcd670d326dc.png)
