### ISSUE TITLE
IOSNotificationAttachment remote .mp3 file not playing

### ISSUE THREAD

**Issue by VivienTournie** [notifee/react-native-notifee#217] opened 2020-12-22 21:53 UTC
Hello,

I'm having troubles playing remote files with **IOSNotificationAttachment**.
Here is my code :

First i'm calling notifee.requestPermission() as explained [in the doc ](https://notifee.app/react-native/docs/ios/permissions#requesting-permissions):

Then here is my config :
    
    `// Create a trigger notification
    await notifee.createTriggerNotification({
        id: notificationId,
        title: titre,
        body: description,
        android: {
            channelId: channelId,
            category: AndroidCategory.ALARM,
            importance : AndroidImportance.HIGH,
            pressAction: {
                launchActivity: "default",
                id: "default",
              },
        },
        ios: {
            foregroundPresentationOptions: {
                alert: true,
                badge: true,
                sound: true,
              },
            attachments: [
                {
                  // Remote .mp3 file
                  url: 'https://cdns-preview-d.dzcdn.net/stream/c-deda7fa9316d9e9e880d2c6207e92260-8.mp3',
                },
            ],
        },
    },
    trigger,
    );
}
`

My settings seems to be correct to me :
`Permission settings: {"alert": 1, "announcement": -1, "authorizationStatus": 1, "badge": 1, "carPlay": -1, "criticalAlert": -1, "inAppNotificationSettings": 0, "lockScreen": 1, "notificationCenter": 1, "showPreviews": 1, "sound": 1}`

The notification is showing correctly, but no sound is playing. I tried with sound: 'default" too, didn't work. I'm using the new mac M1 simulator (iPhone 11, iOS 14.3).
I'm using Notifee version ^0.15.2.

Am I missing something for my .mp3 remote file to be played ?

Thanks !

**Comment by helenaford** [comment] 2020-12-23 19:04
Hi, thanks for the detailed outline of the issue. I was able to recreate this locally on the iOS 14.3 emulator which looks like this could be a potential bug. I can confirm your mp3 file does work on iOS 13 and lower if that helps to continue development while we look into a resolution. Thank you for bringing this to our attention, and apologies for any inconvenience.

**Comment by VivienTournie** [comment] 2020-12-23 23:18
Thanks for the quick answer !

As you can see in my code, i'm using a remote .mp3 file (from Napster API), so I have no file on the device (simulator). So I think we can exclude the hypothesis of file renaming or lack of disk space (at least for this specific case).

I am not using the `thumbnailHidden` property, and since it is set to False by default (according to the documentation) I think it doesn't interfere with this use case ?

Didn't test on iOS 13 and lower for now, will do tomorrow.

**Comment by helenaford** [comment] 2020-12-24 16:28
OK thanks. If you could check the native logs that would help too. Wondering if it's the SpringBoard removing the attachment (like I saw initially). Will keep investigating and watching out for it, but since the attachments started showing up I was unable replicate the negative result.

**Comment by helenaford** [comment] 2021-02-05 23:27
Closing this as I can't recreate locally, please reopen if you still see the issue.

**Closed by helenaford** 2021-02-05 23:27 UTC
Labels: Platform: iOS, blocked: customer-response, under-review
