### ISSUE TITLE
"app:checkDebugDuplicateClasses FAILED" error appears when running run android

### ISSUE THREAD

**Issue by lavi-moolchandani** [notifee/react-native-notifee#75] opened 2020-06-03 15:01 UTC
I just install @notifee/react-native and tried to run 'run-android' command, the error 'app:checkDebugDuplicateClasses FAILED' appears in terminal. I created another blank project with react-native init command and just added my previous package.json file in the new project. still after downloading node_modules, when I ran 'react-native run-android' it show the same error. It might be because of some interdependency of subPackages. I've tried running it without notifee and it runs fine, please have a look at my package.json and help me finding the issue.
[package.txt](https://github.com/notifee/react-native-notifee/files/4724224/package.txt)

**Comment by Ehesp** [comment] 2020-06-03 15:09
Could you share the entire output please?

**Comment by lavi-moolchandani** [comment] 2020-06-04 06:24
@Ehesp this is the entire output I got when I run the command

> Configure project :notifee_react-native
:notifee_react-native package.json found at /Users/lavi/Sites/projects/newAcrobody/demo/node_modules/@notifee/react-native/package.json
:notifee_react-native:version set from package.json: 0.5.1 (0,5,1 - 5001)
:notifee_react-native:android.compileSdk using custom value: 29
:notifee_react-native:android.targetSdk using custom value: 29
:notifee_react-native:android.minSdk using custom value: 16
:notifee_react-native:reactNativeAndroidDir /Users/lavi/Sites/projects/newAcrobody/demo/node_modules/react-native/android

> Configure project :react-native-firebase_app
:react-native-firebase_app package.json found at /Users/lavi/Sites/projects/newAcrobody/demo/node_modules/@react-native-firebase/app/package.json
:react-native-firebase_app:firebase.bom using default value: 25.3.1
:react-native-firebase_app package.json found at /Users/lavi/Sites/projects/newAcrobody/demo/node_modules/@react-native-firebase/app/package.json
:react-native-firebase_app:version set from package.json: 7.2.0 (7,2,0 - 7002000)
:react-native-firebase_app:android.compileSdk using custom value: 28
:react-native-firebase_app:android.targetSdk using custom value: 28
:react-native-firebase_app:android.minSdk using custom value: 16
:react-native-firebase_app:reactNativeAndroidDir /Users/lavi/Sites/projects/newAcrobody/demo/node_modules/react-native/android

> Configure project :react-native-firebase_auth
:react-native-firebase_auth package.json found at /Users/lavi/Sites/projects/newAcrobody/demo/node_modules/@react-native-firebase/auth/package.json
:react-native-firebase_app package.json found at /Users/lavi/Sites/projects/newAcrobody/demo/node_modules/@react-native-firebase/app/package.json
:react-native-firebase_auth:firebase.bom using default value: 25.3.1
:react-native-firebase_auth package.json found at /Users/lavi/Sites/projects/newAcrobody/demo/node_modules/@react-native-firebase/auth/package.json
:react-native-firebase_auth:version set from package.json: 8.0.4 (8,0,4 - 8000004)
:react-native-firebase_auth:android.compileSdk using custom value: 28
:react-native-firebase_auth:android.targetSdk using custom value: 28
:react-native-firebase_auth:android.minSdk using custom value: 16
:react-native-firebase_auth:reactNativeAndroidDir /Users/lavi/Sites/projects/newAcrobody/demo/node_modules/react-native/android

> Configure project :react-native-firebase_dynamic-links
:react-native-firebase_dynamic-links package.json found at /Users/lavi/Sites/projects/newAcrobody/demo/node_modules/@react-native-firebase/dynamic-links/package.json
:react-native-firebase_app package.json found at /Users/lavi/Sites/projects/newAcrobody/demo/node_modules/@react-native-firebase/app/package.json
:react-native-firebase_dynamic-links:firebase.bom using default value: 25.3.1
:react-native-firebase_dynamic-links package.json found at /Users/lavi/Sites/projects/newAcrobody/demo/node_modules/@react-native-firebase/dynamic-links/package.json
:react-native-firebase_dynamic-links:version set from package.json: 7.1.3 (7,1,3 - 7001003)
:react-native-firebase_dynamic-links:android.compileSdk using custom value: 28
:react-native-firebase_dynamic-links:android.targetSdk using custom value: 28
:react-native-firebase_dynamic-links:android.minSdk using custom value: 16
:react-native-firebase_dynamic-links:reactNativeAndroidDir /Users/lavi/Sites/projects/newAcrobody/demo/node_modules/react-native/android

> Configure project :react-native-firebase_firestore
:react-native-firebase_firestore package.json found at /Users/lavi/Sites/projects/newAcrobody/demo/node_modules/@react-native-firebase/firestore/package.json
:react-native-firebase_app package.json found at /Users/lavi/Sites/projects/newAcrobody/demo/node_modules/@react-native-firebase/app/package.json
:react-native-firebase_firestore:firebase.bom using default value: 25.3.1
:react-native-firebase_firestore package.json found at /Users/lavi/Sites/projects/newAcrobody/demo/node_modules/@react-native-firebase/firestore/package.json
:react-native-firebase_firestore:version set from package.json: 7.1.5 (7,1,5 - 7001005)
:react-native-firebase_firestore:android.compileSdk using custom value: 28
:react-native-firebase_firestore:android.targetSdk using custom value: 28
:react-native-firebase_firestore:android.minSdk using custom value: 16
:react-native-firebase_firestore:reactNativeAndroidDir /Users/lavi/Sites/projects/newAcrobody/demo/node_modules/react-native/android

> Configure project :react-native-firebase_functions
:react-native-firebase_functions package.json found at /Users/lavi/Sites/projects/newAcrobody/demo/node_modules/@react-native-firebase/functions/package.json
:react-native-firebase_app package.json found at /Users/lavi/Sites/projects/newAcrobody/demo/node_modules/@react-native-firebase/app/package.json
:react-native-firebase_functions:firebase.bom using default value: 25.3.1
:react-native-firebase_functions package.json found at /Users/lavi/Sites/projects/newAcrobody/demo/node_modules/@react-native-firebase/functions/package.json
:react-native-firebase_functions:version set from package.json: 7.1.3 (7,1,3 - 7001003)
:react-native-firebase_functions:android.compileSdk using custom value: 28
:react-native-firebase_functions:android.targetSdk using custom value: 28
:react-native-firebase_functions:android.minSdk using custom value: 16
:react-native-firebase_functions:reactNativeAndroidDir /Users/lavi/Sites/projects/newAcrobody/demo/node_modules/react-native/android

> Configure project :react-native-firebase_messaging
:react-native-firebase_messaging package.json found at /Users/lavi/Sites/projects/newAcrobody/demo/node_modules/@react-native-firebase/messaging/package.json
:react-native-firebase_app package.json found at /Users/lavi/Sites/projects/newAcrobody/demo/node_modules/@react-native-firebase/app/package.json
:react-native-firebase_messaging:firebase.bom using default value: 25.3.1
:react-native-firebase_messaging package.json found at /Users/lavi/Sites/projects/newAcrobody/demo/node_modules/@react-native-firebase/messaging/package.json
:react-native-firebase_messaging:version set from package.json: 7.1.4 (7,1,4 - 7001004)
:react-native-firebase_messaging:android.compileSdk using custom value: 28
:react-native-firebase_messaging:android.targetSdk using custom value: 28
:react-native-firebase_messaging:android.minSdk using custom value: 16
:react-native-firebase_messaging:reactNativeAndroidDir /Users/lavi/Sites/projects/newAcrobody/demo/node_modules/react-native/android

> Task :react-native-community_async-storage:compileDebugJavaWithJavac

> Task :react-native-device-info:compileDebugJavaWithJavac

> Task :react-native-firebase_auth:compileDebugJavaWithJavac

> Task :react-native-gesture-handler:compileDebugJavaWithJavac

> Task :react-native-firebase_firestore:compileDebugJavaWithJavac

> Task :react-native-haptic-feedback:compileDebugJavaWithJavac

> Task :react-native-reanimated:compileDebugJavaWithJavac

> Task :react-native-screens:compileDebugJavaWithJavac

> Task :react-native-video:compileDebugJavaWithJavac

> Task :sentry_react-native:compileDebugJavaWithJavac

> Task :app:processDebugManifest
/Users/lavi/Sites/projects/newAcrobody/demo/android/app/src/debug/AndroidManifest.xml:24:9-31:50 Warning:
        activity#com.google.firebase.auth.internal.FederatedSignInActivity@android:launchMode was tagged at AndroidManifest.xml:24 to replace other declarations but no other declaration present

> Task :app:compileDebugJavaWithJavac

> Task :app:checkDebugDuplicateClasses FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.0.1/userguide/command_line_interface.html#sec:command_line_warnings
432 actionable tasks: 432 executed
Note: /Users/lavi/Sites/projects/newAcrobody/demo/node_modules/@react-native-community/async-storage/android/src/main/java/com/reactnativecommunity/asyncstorage/AsyncStorageModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/lavi/Sites/projects/newAcrobody/demo/node_modules/react-native-device-info/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/lavi/Sites/projects/newAcrobody/demo/node_modules/@react-native-firebase/auth/android/src/main/java/io/invertase/firebase/auth/ReactNativeFirebaseAuthModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/lavi/Sites/projects/newAcrobody/demo/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerButtonViewManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: /Users/lavi/Sites/projects/newAcrobody/demo/node_modules/react-native-haptic-feedback/android/src/main/java/com/mkuczera/RNReactNativeHapticFeedbackModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/lavi/Sites/projects/newAcrobody/demo/node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/NodesManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/lavi/Sites/projects/newAcrobody/demo/node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/NodesManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: /Users/lavi/Sites/projects/newAcrobody/demo/node_modules/react-native-video/android/src/main/java/com/android/vending/expansion/zipfile/APEZProvider.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/lavi/Sites/projects/newAcrobody/demo/node_modules/react-native-video/android/src/main/java/com/brentvatne/react/ReactVideoViewManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: /Users/lavi/Sites/projects/newAcrobody/demo/node_modules/@sentry/react-native/android/src/main/java/io/sentry/RNSentryModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/lavi/Sites/projects/newAcrobody/demo/android/app/src/debug/java/com/demo/ReactNativeFlipper.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: java.lang.RuntimeException: Duplicate class com.google.common.util.concurrent.ListenableFuture found in modules guava-26.0-android.jar (com.google.guava:guava:26.0-android) and listenablefuture-1.0.jar (com.google.guava:listenablefuture:1.0)

  Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5m 7s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
Note: /Users/lavi/Sites/projects/newAcrobody/demo/node_modules/@react-native-community/async-storage/android/src/main/java/com/reactnativecommunity/asyncstorage/AsyncStorageModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/lavi/Sites/projects/newAcrobody/demo/node_modules/react-native-device-info/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/lavi/Sites/projects/newAcrobody/demo/node_modules/@react-native-firebase/auth/android/src/main/java/io/invertase/firebase/auth/ReactNativeFirebaseAuthModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/lavi/Sites/projects/newAcrobody/demo/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerButtonViewManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: /Users/lavi/Sites/projects/newAcrobody/demo/node_modules/react-native-haptic-feedback/android/src/main/java/com/mkuczera/RNReactNativeHapticFeedbackModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/lavi/Sites/projects/newAcrobody/demo/node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/NodesManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/lavi/Sites/projects/newAcrobody/demo/node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/NodesManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: /Users/lavi/Sites/projects/newAcrobody/demo/node_modules/react-native-video/android/src/main/java/com/android/vending/expansion/zipfile/APEZProvider.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/lavi/Sites/projects/newAcrobody/demo/node_modules/react-native-video/android/src/main/java/com/brentvatne/react/ReactVideoViewManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: /Users/lavi/Sites/projects/newAcrobody/demo/node_modules/@sentry/react-native/android/src/main/java/io/sentry/RNSentryModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/lavi/Sites/projects/newAcrobody/demo/android/app/src/debug/java/com/demo/ReactNativeFlipper.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: java.lang.RuntimeException: Duplicate class com.google.common.util.concurrent.ListenableFuture found in modules guava-26.0-android.jar (com.google.guava:guava:26.0-android) and listenablefuture-1.0.jar (com.google.guava:listenablefuture:1.0)

  Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5m 7s

    at makeError (/Users/lavi/Sites/projects/newAcrobody/demo/node_modules/execa/index.js:174:9)
    at /Users/lavi/Sites/projects/newAcrobody/demo/node_modules/execa/index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async runOnAllDevices (/Users/lavi/Sites/projects/newAcrobody/demo/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:94:5)
    at async Command.handleAction (/Users/lavi/Sites/projects/newAcrobody/demo/node_modules/react-native/node_modules/@react-native-community/cli/build/index.js:186:9)

**Comment by Ehesp** [comment] 2020-06-04 08:28
Looks like another package uses an Android dependency which is clashing. You have a lot of other packages installed so finding the cause maybe tricky...

Within your project, could you show the results of: `cd android && ./gradlew :app:dependencies`

Essentially, [this](https://stackoverflow.com/questions/56716047/execution-failed-for-task-appcheckdebugduplicateclasses-ionic4-android) is a similar issue.

**Comment by Ehesp** [comment] 2020-06-04 08:33
Actually, seems like this could be related to Android Studio update... What version are you using? cc https://github.com/notifee/react-native-notifee/issues/68#issuecomment-636350392

**Comment by lavi-moolchandani** [comment] 2020-06-04 10:33
@Ehesp I am using android studio 3.5

**Comment by Ehesp** [comment] 2020-06-04 11:49
Could you show the outputs of the gradle list dependencies task then please?

**Comment by iwikal** [comment] 2020-06-25 11:03
I think I'm having the same issue. It started happening when I upgraded to react-native-firebase v6, but when I remove notifee the problem goes away.
https://gist.github.com/iwikal/870127d6f1d6e8c2a3567b2d8ca5a52d

**Comment by mikehardy** [comment] 2020-06-25 17:53
@iwikal You need this from the linked issue 3 comments above https://github.com/notifee/react-native-notifee/issues/68#issuecomment-636350392

**Comment by mikehardy** [comment] 2020-06-25 17:54
I'm going to close this as it is either resolved for the OP (no one sits on a build error for 22 days!) or resolved with related issues. Future people that hit this: please read linked comments they have actionable solutions, thanks!

**Closed by mikehardy** 2020-06-25 17:54 UTC

**Comment by iwikal** [comment] 2020-06-25 19:07
@mikehardy Thanks, that worked! I glossed over that thread initially because I'm not using Android Studio so I thought it wouldn't apply to me, plus I saw that exact dependency in my dependency graph so I didn't think adding it would make any difference, but I'm exhilarated to discover how wrong I was!
