### ISSUE TITLE
Trigger Function Release

### ISSUE THREAD

**Issue by naufanituharish** [notifee/react-native-notifee#98] opened 2020-07-03 01:44 UTC
I just purchase the license for notifee package, so I just wondering when the trigger function will be released??

**Comment by Salakar** [comment] 2020-08-06 20:01
@helenaford is landing an initial release for this right now for Android, see: https://notifee.app/react-native/docs/triggers

**Comment by Salakar** [comment] 2020-08-06 20:17
Closing as duplicate of https://github.com/notifee/react-native-notifee/issues/36

**Closed by Salakar** 2020-08-06 20:17 UTC
